#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 25 16:39:19 2017

@author: JAK
"""

# Plotting of BB and moving averages

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.dates as mdates

# Historic Data
BTCKrakenData = pd.read_csv('HistoricalData/KrakenBTC-USDPriceData.csv')
BTCExchangeData = pd.read_csv('HistoricalData/ExchangesBTC-USDPriceData.csv')

# Date Array
dates = BTCExchangeData.iloc[:,0].values
dates = np.array(dates)
dates = dates.astype(np.str)



dates_dateTime = [dt.datetime.strptime(d,'%Y-%m-%d').date() for d in dates]

# Average BTC Price from exchanges
averageBTCPrice = BTCExchangeData.iloc[:,5].values
averageBTCPrice = np.array(averageBTCPrice)
averageBTCPrice = averageBTCPrice.astype(np.float)



start_date = '2017-9-13'


# PLOTTING

start_date_dateTime = dt.datetime.strptime(start_date, '%Y-%m-%d').date()
start_index = dates_dateTime.index(start_date_dateTime )

plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
#plt.gca().xaxis.set_major_locator(mdates.DayLocator())
plt.plot(dates_dateTime[start_index:len(dates_dateTime)],averageBTCPrice[start_index:len(dates_dateTime)])
plt.gcf().autofmt_xdate()
plt.show()


